name: groo_up
description: Groo-up — Grow your ideas like a tree
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  supabase_flutter: ^2.5.0
  dio: ^5.4.3
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  lottie: ^3.1.2
  rive: ^0.13.5
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  gap: ^3.0.1
  cached_network_image: ^3.3.1
  home_widget: ^0.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.19.0
  logger: ^2.3.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/rive/
    - assets/images/
    - assets/fonts/public/variable/
  fonts:
    - family: PretendardVariable
      fonts:
        - asset: assets/fonts/public/variable/PretendardVariable.ttf
